### ISSUE TITLE
Can't find all the DGE files

### ISSUE THREAD

**Issue by zuoyi93** [eddieimada/fcr2#1]
Dear Dr. Imada,

Thanks for sharing this amazing repository, and it's a great learning resource!

However, I couldn't find the DGE files at the following location, nor could I generate them from the existing code. Did I miss anything here or is there a way to extract that information from the `recount` package?

https://github.com/eddieimada/fcr2/blob/9c5bb196fd3cfb790b7d34e5276dbfb212568cc7/TCGA/PaperCode/03geneCount.R#L15-L16

Thanks in advance!

Yi

**Comment by eddieimada** [comment]
Dear Yi,

I’m very glad you find our resource useful! 

The DGE files are not in the repository because they are too many. They can be generated using: https://github.com/eddieimada/fcr2/blob/9c5bb196fd3cfb790b7d34e5276dbfb212568cc7/TCGA/DGE/01voom.R
You will need to run it for every class of RNA and Cancer type though. Right now, I don't have easy access to them, but I can look if I still have them and send to you some time later if you send me an address.

Also, we recently released a new version of recount containing over 750,000 samples. If you want to check out:
https://www.biorxiv.org/content/10.1101/2021.05.21.445138v1.abstract

Feel free to reach out if you have any further questions.

Eddie.

**Comment by zuoyi93** [comment]
Dear Dr. Imada,

Thanks for your prompt response! I will use the `01voom.R` script to generate the DGE files! Also thanks for pointing me to the `recount3` package and I will definitely give it a read.

Thanks again!

Best,

Yi
